server:
    port: 3005
    error:
      include-message: always
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    #url: jdbc:h2:file:./data/testdb
    driverClassName: org.h2.Driver
    username: test
    password: test
  servelet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  flyway:
      enabled: true
# set file base memory so data will not lost when application restart
#spring.datasource.url=jdbc:h2:file:/data/demo
#http://localhost:3005/h2-console/login.jsp?jsessionid=024e4a2143b945f65fe58836e656360c

jwt:
  signing:
    key: kRQsxfkt|+%}}8,LG#]9s/W2_fR54x
  header:
    string: Authorization
  authorities:
    key: roles
  token:
    prefix: Bearer
    updateineachrequest: false
    validity: 7200

swagger:
  enable: false